language: python

python:
- 3.9
- 3.8
- 3.7
- 3.6

before_install:
- pip install --upgrade pip
- pip install --upgrade -r test-requirements.txt

install:
- pip install .

script:
- pytest

after_script:
- coveralls

env:
  global:
  - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
