name: Coveralls Upload

on:
  workflow_call:
    secrets:
      github_token:
        required: false

jobs:
  coveralls:
    name: Indicate completion to coveralls.io
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
